### ISSUE TITLE
[LAHI] User is able to register students in Avni

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/LAHI#1]
**Motivation:**
Vindhya (BPO) users receive details of Students through a google form shared with Students using Gliffic. Once they receive the details of Students, they are required to fill this data in Avni - they may also get on call with student for verification or to take details on specific fields. Once the integration of Gliffic is done - this data will be pulled from Gliffic to directly into Avni, for now the users will do entries fromspreadsheets.

**Goal:**
 Users are able to register Student details in Avni application with all the necessary details as provided in the requirements.
Student Subject type - Person
Location - State and District
Form Requirements: 
https://docs.google.com/spreadsheets/d/1C0OIflblJZB2z8qcfxaC0dZtNzdtudbOJf5asZSMr1E/edit#gid=0

**Acceptance Criteria:**
User should be able to register Student details in the application. They should be able to enter middle name of Students and the form should also display Full name of student based on First name, middle name and Last name. It must satisfy all the validation criteria provided for each field in the requirements. 

**Test Scenarios:**
1. Full name is displayed as "First Name" + "Middle Name" + "Last Name" (skip middle name, if not available)
2. Unique check on E-mail id: User should not be able to register a student with same email address.

**Comment by AchalaBelokar** [comment]
1) Validation is required for First name and last name.
2) Parent's Contact Number field is missing.
3) Validation is required for the pin code number.
