### ISSUE TITLE
[LAHI] Volunteer is able to complete follow-up with student for TechMahindra Application

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/LAHI#11]
**Motivation:**
Volunteers follow-up with Students after enrolling them in "TechMahindra - Application" Program to help them proceed with the application, take updates from student and help them answer their concerns. 

**Goal**
1. Volunteer enrolls student in "TechMahindra - Application" program and on enrollment first follow-up visit for the same date is scheduled named "TechMahindra - Application follow-up 1"
2. User updates details in the follow-up form after interacting with student.
3. User updates the Status for Program in the form.
4. User  gives a date for next follow-up if it is required.
5. Next follow-up visit "TechMahindra - Application follow-up 2" is scheduled on the date provided by volunteer on submitting the form.
6.  Whenever user submits a follow-up visit with a follow-up date, it should schedule the next follow-up form with name "TechMahindra - Application follow-up n" where n is the number of follow-up. i.e. 3,4 etc.
7. The follow-up visit populates answers for fields recorded in previous follow-up.

**Acceptance Criteria:**
User is able to enroll the student in the program and do follow-up visits with required criteria as mentioned in the form:

**Acceptance Criteria:**
User is able to enroll the student into "TechMahindra - Application" program and subsequently complete the follow-up visits with required criteria as mentioned in the form.

"TechMahindra- Application follow-up" Form Requirements:
https://docs.google.com/spreadsheets/d/1cNTvtvBl8Yh7JtGIZFNdeOhlP8iC1wf_8ePdsdzR6qc/edit#gid=1851887719

**Comment by AchalaBelokar** [comment]
The name of the course is missing in the form.
City in which course is offered? is missing.
