### ISSUE TITLE
[LAHI] Program for enrolment to be visible based on Eligibility Status

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/LAHI#23]
**Motivation:**
After a student is determined eligible for specific Programs, they have to go through the application process before joining a program. Avni is required to have specific Programs for Applying to these different programs. Only the programs for which students are eligible should be visible for enrollment.

**Goal:**
Program Eligibility encounter records eligibility for different programs.  Program(s) where eligibility is Yes should be visible for enrolling the student. If eligibility is No for a specific program, those programs are not visible.

**Acceptance Criteria:**
User completes Program Eligibility encounter for a Student and Eligibility for a single or multiple program is updated. 
The system should only show Programs for which Eligibility is Yes, and not show if it is updated as No.
The system should check all Program eligibility encounters to determine which programs to show.
i.e. if NavGurukul - Eligibility is updated as Yes, the Enrollment option in Student profile shows "Apply for NavGurukul" Program. 
If user goes back, updates details in Program eligibility encounter and Eligibility is updated as No, then the program "Apply for NavGurukul" should not be visible for enrollment in Student profile.

**Comment by AchalaBelokar** [comment]
Masai School Eligibility is not showing the correct answer.
The student is eligible for  program but still it is showing no answer
