### ISSUE TITLE
[LAHI] User is able to register Partner details in the application.

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/LAHI#3]
Motivation:
Partners are organizations which offer different program to students. The details of organization along with contact details of a person who is point of contact are required to be updated in application along with different programs which are offered. This will be useful to LAHI in internal reporting.

Goal:
User is able to register partner details in application.
Subject Type: Individual
Location: State, District, City
Form: Partner Registration

Acceptance criteria:
User should be able to update Partner details along with programs offered based on the requirement details provided in the sheet mentioned below:
https://docs.google.com/spreadsheets/d/19RU51VmviwYgB8cgHl8wWtvY7PXm_6DFjSepm0eNWHI/edit#gid=1405876534

**Comment by AchalaBelokar** [comment]
1) The mode of implementation is multi-select
2 ) Residential Requirement is multi- select
3)
