### ISSUE TITLE
[LAHI] UAT Feedback

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/LAHI#30]
***Wherever changes are there in requirement sheets, cells have been highlighted in green in respective sheets.**
Drive link for Forms:
https://drive.google.com/drive/u/1/folders/1Ko-FH5BbTdPA_ybKbeafM1_UysP5vhnA

- [x] Restrict Student Age to between 14 and 25. Add validation for this in Date of birth.
- [x] Upload State, District, Block, School Name and UDISE code mapping. Based on State, District options will show, subsequently blocks should be displayed based on District. Based on Block, School Name will be displayed and based on School name, the UDISE code should be auto-populated. Currently data is available for Maharashtra.
https://docs.google.com/spreadsheets/d/1v_XIAHGY9sydGLP2Me0gahbzYb_BPDs_/edit#gid=1998659620
- [x] Add Other School and Other School Name questions in Student registration.
- [x] Add "Are you interested in higher education, employment, skilling or internship?" question in Registration.
- [x] Keep "Does Student give permission to LAHI to Send Whatsapp/SMS/Call for any career opportunities" question after the question mentioned above. Sequence updated in Registration sheet.
- [x] Add date validations for date fields in Application follow-up forms of different programs - details added in requirement sheet of all programs.
- [x] Remove Program Status field from Program Enrollment Form
- [x] Skip logic and Mandatory/Non-mandatory to be done as per LAHI requirement sheet. Changes done in requirement sheet of Follow-up encounters for all Programs.
- [x] Hide Unplanned visits within the Programs.
- [ ] Add Program name in Search filter field. **Not doable in Avni right now**
- [x] Remove Percentage criteria from HCL Program eligibility and add Academic year criteria to be 2021-21 or 2021-22. Updated in requirement sheet. 
- [x] Verify NavGurukul - Eligibility criteria as given in the requirement sheet.
- [x] Verify Masai School - Eligibility criteria as given in the requirement sheet.
- [x] Remove "Is follow-up required" in Program Eligibility form.
- [x] Show Eligibility criteria in the form and the fields for the students - at the top of the form in DEA.

**Comment by AchalaBelokar** [comment]
![Screenshot 2022-09-07 at 1.32.12 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/26a9b2b9-edfd-47dd-a0c3-e4953587a1bf)
Why is no option available showing in the form

**Comment by AchalaBelokar** [comment]
- [ ] If we are capturing the middle name on 1st page so why we are capturing it on the second page?

- [ ] we need to add a rule for 14 years of age currently it is starting from the age 15year 25 above not allowed 

- [x]  Navgurual Eligibility is not showing. **Fixed**

- [ ]

**Comment by AchalaBelokar** [comment]
- [ ]  Restrict Student Age to between 14 and 25. Add validation for this in the Date of birth. not reflecting

**Comment by AchalaBelokar** [comment]
- [x]  Restrict Student Age to between 14 and 25. Add validation for this in the Date of birth. not reflecting
