### ISSUE TITLE
[LAHI] Program Status auto-update after enrolment

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/LAHI#31]
**Motivation:**
Once a student is enrolled in program, Program Status need to be displayed by system based on answers provided during follow-ups.

Logic updated in requirement sheet for each program.

- [x] HCL Techbee Program Status 
https://docs.google.com/spreadsheets/d/1qAzNKKh54Y_3xLixdMZhHL8r4blW0P9NnrZlgvqtsb8/edit#gid=1610401046
- [x] MagicB Status
https://docs.google.com/spreadsheets/d/1GBzqhZVLvt0RppJuZeiibB8CyY3CjZDPMzniynLVT2U/edit#gid=701606418
- [x] Masai School Status
https://docs.google.com/spreadsheets/d/1hXOb0NlVhGF7Dr8hAKJ-RHrMtmuqxI3adWY5qKd-hTI/edit#gid=1801080461
- [x] NavGurukul Status
https://docs.google.com/spreadsheets/d/1lymbUOjvoElVJp0JK4UYP-HGw54jZ0etx8FZi8OhrXU/edit#gid=1325866945
- [x] TechM Status
https://docs.google.com/spreadsheets/d/1cNTvtvBl8Yh7JtGIZFNdeOhlP8iC1wf_8ePdsdzR6qc/edit#gid=2039510510

**Comment by utkarshavni** [comment]
Awaiting queries' response from client for following programs:
1. MagicB
2. TechM
3. NavGurukul

**Comment by utkarshavni** [comment]
Following issues:
- [x] For Navgurukul, when Result of 1st interview is Fail, the status should be Rejected. There was no value in the logic provided for fail, i have added.
- [x] For Masai school, when Joined the program is Yes, the status shows selected - it should be Joined.
- [x] For TechM when interview scheduled answer is No, then status should be In process only - have changed this logic in requirement.

**Comment by utkarshavni** [comment]
- [x] HCL - When CAT Exam scheduled is no more interested - it should update program status as dropped out/not interested. This was not present in given logic by LAHI, have updated it in sheet.

**Comment by utkarshavni** [comment]
- [x] HCL-TechBee - When CAT-1 exam result is Fail and Interested for Re-exam is "No", it shows HCL TechBee Status as "Applied" -  it should be "Drop out/Not interested Anymore"
- [x] HCL-TechBee - When CAT-2 exam result is "Fail", HCL TechBee status still shows "Applied", it should be "Rejected".
- [x] Except Navgurukul, all other program status are not displayed on Webapp.

**Comment by utkarshavni** [comment]
Have moved it to QA failed since this needs to work for Web app in the encounters which is not working right now. Both Program Status and Program Application status are not displayed in the Application follow-up encounters.

**Comment by Gojo-Taqi** [comment]
Created a bug card for it.
https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/avni-webapp/822

**Comment by utkarshavni** [comment]
Closing this card as the product bug is resolved and both Program Status and Program Application Status are displayed in web app for all programs.
