### ISSUE TITLE
[LAHI] UAT Feedback issues

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/LAHI#33]
- [x] Add following filters for Search (Students) in web app.
      1. Phone number (Contact number concept)
      2. All locations.
      3. Gender
      4. Highest Qualification
- [x] HCL Eligibility is updated as NO in following conditions. It should be updated as Yes.
     - 12th-HSC, Appearing, Academic year 2020-21, Math/Business Math
     - 12th-HSC, Appearing, Academic year 2021-22, Math/Business Math
     - 12th-HSC, Results awaited, Academic year 2021-22, Math/Business Math
     - 12th-HSC, Results awaited, Academic year 2021-22, Math/Business Math
     - 12th-HSC, Pass out, Academic year 2020-21, Math/Business Math
- [x] In HCL Application follow-up, for "Interview-1" field, date validation "Date cannot be on or before the date of CAT 2 - rescheduled" is shown even when "Date of CAT-Reschduled  (CAT-2) Exam" is not there. The validation should show based on "CAT-1 exam Date" or "CAT-Rescheduled (CAT-2) Exam" whichever is available. If both are available, it should consider the rescheduled date for validation.
- [x] Same issue as above to be resolved for Navgurukul as well.
- [x] For Navgurukul Application follow-up, if no date for first interview has been provided, date for 2nd interview should not throw a validation.
- [x] For all the programs' follow-up encounter, the "Next follow-up date" should not allow the date on which that encounter is filled or a date before that.
- [x] For Navgurukul Application follow-up, even when last mandatory question answered is "Result of 1st interview" and answer is failed, it shows Application Status as Result of 1st interview available. Check 12th slide in below given link:
https://docs.google.com/presentation/d/1TV6mlpXjwOsP54yU28CG-wV24_l8Qq0QHVkq70REvqc/edit#slide=id.g155220def2d_0_8

**Comment by kannangudalur** [comment]
@nupoorkhandelwal Can you please check point 2

**Comment by utkarshavni** [comment]
Removed dashboard item since creating a new card for that.
https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/lahi/36

**Comment by AchalaBelokar** [comment]
Add the following filters for Search (Students) in web app. missing this concept
1. Phone number (Contact number concept)

**Comment by utkarshavni** [comment]
Closing this card since it was tested before previous show case and things were working fine.

**Comment by utkarshavni** [comment]
Phone number search filter not available in webapp.

**Comment by AchalaBelokar** [comment]
- [ ]  Phone number (Contact number concept) is not working in web app

**Comment by AchalaBelokar** [comment]
- [ ]  Phone number (Contact number concept) is not working in web app

**Comment by AchalaBelokar** [comment]
- [ ]  Phone number (Contact number concept) is not working in web app

**Comment by AchalaBelokar** [comment]
- [ ]  Phone number (Contact number concept) is not working in web app

**Comment by AchalaBelokar** [comment]
- [ ]  Phone number (Contact number concept) is not working in web app

**Comment by AchalaBelokar** [comment]
- [ ]  Phone number (Contact number concept) is not working in web app

**Comment by AchalaBelokar** [comment]
- [ ]  Phone number (Contact number concept) is not working in web app

**Comment by AchalaBelokar** [comment]
- [ ]  Phone number (Contact number concept) is not working in web app

**Comment by AchalaBelokar** [comment]
- [x]  Phone number (Contact number concept) is not working in web app

**Comment by sachsk** [comment]
I have fixed the search with mobile no. issue
Replaced the numeric dataType with text dataType
