### ISSUE TITLE
[LAHI] Custom offline dashboard for Students

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/LAHI#36]
Custom offline dashboard for Students:

Dashboard requirements:
https://docs.google.com/spreadsheets/d/1LyqTwuErh4o7Qw8WD1idhdLqGl0_GGf7T7btCBxbV30/edit#gid=683615866

**Acceptance criteria:**
1. Make this primary dashboard for Volunteer.
2. Clicking on the folder should take the user to linelist of the students.
3. It should only display count and list of students for the program which the volunteer is assigned to.
4. It should not display students who have exited the program.

**Comment by utkarshavni** [comment]
The program status cards do not show count and are not updated after enrolling students in programs. The subject assignment feature was not there in UAT earlier, now we have assigned students to users. Not sure if that has created any issue.

**Comment by AchalaBelokar** [comment]
Offline dashboards is not working

**Comment by AchalaBelokar** [comment]
when I edit the student which is earlier in interest but not applied after editing it goes in to the joined program and appears in interested but not applied.
user name AchalaB@lahiuat
student name CC

**Comment by Gojo-Taqi** [comment]
I figured out the problem, no code changes or anything was done, there was only mistake in understanding the context behind it.
Will explain it to Achala over the call.
