### ISSUE TITLE
[LAHI] Misc items

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/LAHI#40]
- [x] Web App - For HCL TechBee program - HCL TechBee status is not displayed in Program summary. 
- [x] Web App and Android - For Techmahindra, Masai School and Magic Billion Program, both Program status and Application status are missing in program summary.

**Comment by AchalaBelokar** [comment]
It is not  showing program summary

**Comment by AchalaBelokar** [comment]
It is not  showing program summary

**Comment by Gojo-Taqi** [comment]
Fixed

**Comment by AchalaBelokar** [comment]
Not fixed yet

**Comment by AchalaBelokar** [comment]
Not fixed yet

**Comment by AchalaBelokar** [comment]
Not fixed yet

**Comment by AchalaBelokar** [comment]
Not fixed yet

**Comment by AchalaBelokar** [comment]
Not fixed yet

**Comment by Gojo-Taqi** [comment]
The rule is not working for one individual so far.
For now moving it back to QA ready and once I have some free time, I will look into that individual on why it's not working.
