### ISSUE TITLE
[LAHI] Go Live tasks

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/LAHI#42]
- [x] Create a new prod instance for LAHI with db schema name as "lahi" (Existing org "Lend a Hand India" to be used for going live.)
- [x] Upload bundle from LAHI UAT in new instance without the locations.
- [x] Upload locations.
https://docs.google.com/spreadsheets/d/1h6T9DBEVa4pilZdQO6-mOxS0X3Ghpck7/edit?usp=drive_web&ouid=100265945917284170678&rtpof=true
- [x] Upload users and Catchment.
https://docs.google.com/spreadsheets/d/1qKPNbEl1Let7oCrU_wzx6MI-mGXHgAHzqBsR77tBuGY/edit#gid=2011782492
- [x] Configure User groups and provide permissions.
- [x] Make Program follow-up encounters as Immutable.
- [x] Make Student Dashboard primary for users.

**Comment by AchalaBelokar** [comment]
The splash screen is not working
