### ISSUE TITLE
[LAHI] Generating Unique id for Student Registration

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/LAHI#43]
A unique id (LAHI Id) needs to be generated by system during the Student registration process to avoid duplicate registration.  

Student Registration form:
https://docs.google.com/spreadsheets/d/1C0OIflblJZB2z8qcfxaC0dZtNzdtudbOJf5asZSMr1E/edit#gid=0

**Comment by himeshr** [comment]
This is pending Analysis and response from LAHI team..

**Comment by utkarshavni** [comment]
@himeshr Just want to add that there is a new product feature for Unique ID for which Arjun has been in touch with LAHI team and a separate budget has been approved of it. Mentioning this since i am not sure if your note is about the same or something else.

**Comment by himeshr** [comment]
oh okay, ya, didn't know about this. Will keep that in mind.

Kind regards,
    Himesh R

**Comment by arjunk** [comment]
This would be a work involving writing integration integration service. So should be picked up by the platform team and tracked on platform wall once full solutioning and budgeting are done. Marking it closed from here.
