### ISSUE TITLE
[LAHI support ]Fix offline dashboard 

### ISSUE THREAD

**Issue by sachsk** [avniproject/LAHI#44]
Ticket : https://avni.freshdesk.com/a/tickets/2235

**Comment by utkarshavni** [comment]
- [x] When a student has not been enrolled in program, status is displayed based on values in Program eligibility encounter which is correct. However, once we enroll the student in a program, and Follow-up encounter is yet to be completed - the status value count is not displayed on dashboard. As long as program encounter is not filled, it should bring the status from program eligibility encounter.
