### ISSUE TITLE
[LAHI] The System should record and determine student eligibility for a program.

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/LAHI#5]
**Motivation:**
Vindhya (BPO) users interact with Students on the programs they are interested in, fill the details in application and based on criteria such as education, age, gender and other program specific criteria, it is determined whether the student is Eligible for specific program or not.

**Goal:**
User completes a general encounter named  "Program Eligibility" for the Student where different questions are asked to students based on specific programs they are interested in and depending on the answers and details provided in Registration and the application determines the Eligibility based on the criteria.

**Acceptance Criteria:**
User should be able to complete the Program Eligibility encounter where:
Program specific pages and questions are shown/hidden based on program interested.
Eligibility is auto calculated based on given criteria.
User is able to update Status of the Program for Student.
User is able to fill a new encounter for "Program Eligibility" when student shows interest for another program.

Program Eligibility Form Requirements:
https://docs.google.com/spreadsheets/d/1C0OIflblJZB2z8qcfxaC0dZtNzdtudbOJf5asZSMr1E/edit#gid=1828223108

**Comment by nupoorkhandelwal** [comment]
Estimate - 2hr

**Comment by AchalaBelokar** [comment]
HCL Program Eligibility 
1) Math or Business Math required validation of not more than 100% 
2) Total Percentage in the 12th field is missing.
3) HCLTechBee Status appears automatically if a student  % is above 60 but now we have to click on remarks. after that, it is appearing.
4) remarks: The first letter of each word to be capital

Masai - Program Eligibility
2) remarks: The first letter of each word to be capital
