### ISSUE TITLE
[LAHI] Sync Students registration information from Glific to Avni 

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/LAHI#51]
**Use case:**
Once a student is sent a message over whatsapp from LAHI to express and confirm their interest in program(s), student will share their basic information such as Name, Gender, Age, School, etc. in response.
When the details are available in Gliffic, Avni needs to bring those details and store for student registration.

**LAHI Glific Integration config document**
https://docs.google.com/spreadsheets/d/191uuBE2R9Q8U0WKfBDsfECX0OiI0zXHpjkBxiZPeK58/edit?usp=sharing

**Registration form requirements:**
https://docs.google.com/spreadsheets/d/1C0OIflblJZB2z8qcfxaC0dZtNzdtudbOJf5asZSMr1E/edit#gid=0

**Comment by arjunk** [comment]
This work was picked up by product team, tracked on product wall and has been completed. Marking this as closed.
