### ISSUE TITLE
[LAHI] Partner wise reports

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/LAHI#55]
- [x] Partner Report - HCL  
Requirements:
https://docs.google.com/spreadsheets/d/12M7sKauGH732iw5FJgWSz6m3-r1muzxUrLQMfn9WmKM/edit#gid=661333098

- [x] Partner Report - NavGurukul
Requirements:
https://docs.google.com/spreadsheets/d/12M7sKauGH732iw5FJgWSz6m3-r1muzxUrLQMfn9WmKM/edit#gid=715965829

**Comment by Gojo-Taqi** [comment]
ETC :- 60 mins

**Comment by arjunk** [comment]
requires another 60 mins to dev complete this story

**Comment by Gojo-Taqi** [comment]
You can find the reports here
https://reporting.avniproject.org/collection/453-lahi

**Comment by Dinesh2019** [comment]
- [x]  For NavGurukul we are missing below columns in report 
        Result of 1st entrance (reappeared)  ---- no concept for this header

**Comment by utkarshavni** [comment]
@Gojo-Taqi  @dinesh2096   Result of 2nd entrance exam column is available which can be used to bring the value - rename the report column to Result of 2nd entrance exam.
