### ISSUE TITLE
[LAHI] Program-State report

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/LAHI#56]
- [x] State Report - Snapshot 
Requirements:
https://docs.google.com/spreadsheets/d/12M7sKauGH732iw5FJgWSz6m3-r1muzxUrLQMfn9WmKM/edit#gid=1020159795

Filters - Gender

**Comment by Gojo-Taqi** [comment]
ETC :- 2 hrs

**Comment by Dinesh2019** [comment]
we have scenario where we have the inconsistency for  data 
 in database with lead to have data mismatch for this report

**Comment by Dinesh2019** [comment]
Moving this card to on hold due to above issue
