### ISSUE TITLE
After 3.38.1 release, update message rule

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/LAHI#57]
https://app.avniproject.org/#/appDesigner/encounterType/1814/show - Here adding of day can be removed from the message rule once this card: https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-server/538 - is released as part of 3.38.1.

**Comment by vinayvenu** [comment]
@mahalakshme @utkarshavni @nupoorkhandelwal 3.38.1 release is complete.
