### ISSUE TITLE
Offline dashboard report optimisation 

### ISSUE THREAD

**Issue by sachsk** [avniproject/LAHI#62]
Optimise the offline report card 
To optimise queries please follow this document : https://avni.readme.io/docs/offline-reports#tips-for-writing-optimized-queries

- [x] Total Members
- [x] Total Students
- [x] Total enrolments
- [x] Total Interns
- [x] Total Alumni
- [x] Karigar Batches
- [x] Interested but not applied
- [x] Selected
- [x] Rejected
- [x] Applied
- [x] Dropped Out / Not Interested Anymore
- [x] Joined program
- [x] In process
- [x] Higher Technical Edcuation
- [x] Not contacted in this Month
- [x] Higher Education
- [x] Upskilling
- [x] Employed

**Comment by vedfordev** [comment]
created feature request in avni-model 
https://github.com/avniproject/avni-models/issues/50

**Comment by Dinesh2019** [comment]
Test execution video :

https://drive.google.com/drive/folders/1-hiA_zlReg4ZnTeVy-_2ej0Csw1EewpW

**Comment by vedfordev** [comment]
prod org bundle backup[Lend a Hand India.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2ZyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a46db8588f5f377ab2cf39716692534af0497f4d/Lend%20a%20Hand%20India.zip)

**Comment by vedfordev** [comment]
### Perfomance 

| Report Card | Old (ms) | New(ms) |
| --- | --- | --- |
| Total Members | 6 | 5 |
| Total Students | 8 | 1 |
| Total enrolments | 7 | 1 |
| Total Interns | 6 | 4 |
| Total Alumni | 16 | 4 |
| Karigar Batches | 10 | 5 |
| Interested but not applied | 207 | 11 |
| Selected | 190 | 5 |
| Rejected | 191 | 5 |
| Applied | 189 | 7 |
| Dropped Out / Not Interested Anymore | 191 | 8 |
| Joined program | 189 | 5 |
| In process | 191 | 6 |
| Higher Technical Edcuation | 48 | 11 |
| Not contacted in this Month | 11 | 5 |
| Higher Education | 48 | 11 |
| Upskilling | 31 | 4 |
| Employed | 35 | 5 |
