### ISSUE TITLE
[LAHI] Partner Report - TechM

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/LAHI#65]
**Context**
A report to show details of all the enrolled student's progress in the TechMahindra program.

**Goal**
- [x] Create linelist report for titled "Partner Report - TechMahindra"
https://docs.google.com/spreadsheets/d/12M7sKauGH732iw5FJgWSz6m3-r1muzxUrLQMfn9WmKM/edit#gid=966183956

Reports folder:
https://reporting.avniproject.org/collection/453-lahi

**Acceptance criteria**
- Report to show all the students' enrolled in TechMahindra Program.

**Comment by vedfordev** [comment]
@sachsk 

I enabled Active analytics data sync for **Lend-a-hand-india UAT**. but I am unable to see etl table. Please check once.
