### ISSUE TITLE
[LAHI] Partner, Volunteer and Total Student Report

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/LAHI#69]
**Context**
The report is required to help the Lend a hand India team in giving an overview of following indicators:
- Number of students enrolled in different programs by user assigned
- Number of students enrolled in different programs by gender

**Goal**
- [x] Create an aggregate report titled "Partner, Volunteer and Total student report" as given in requirements below:
https://docs.google.com/spreadsheets/d/12M7sKauGH732iw5FJgWSz6m3-r1muzxUrLQMfn9WmKM/edit#gid=1594961864
- [x] Provide Filter for State and District - Filter to be applied on the Student's Registration address

**Acceptance criteria**
- The report should display the count for all the programs in which students are enrolled
- The filters for State and District should provide list of locations for the user to select and on applying, only students from those State/District should be displayed.

**Comment by sachsk** [comment]
Tech notes:
Needs to hard-code program in this report so if they add program in future report will not shows data for that program (we need to add it manually)

**Comment by vedfordev** [comment]
## Developer's Note:

#### Logic :
As per tech lead suggestion created query for each program separately and join together. Provided filter as per requirement.


#### Issue:
we have problem with karigar program in prod db.So, it is not included. @utkarshavni @sachsk

**Comment by Dinesh2019** [comment]
1.We have the issue with Lakme

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbUIxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e4927b5e3741205231d124976b22b7f1506ee408/Screenshot%202023-09-07%20at%208.47.51%20AM.png

**Comment by vedfordev** [comment]
@sachsk @utkarshavni 

User **saeed@lendahanduat** changed rule in lakme visit schedule and there is no encounter type as F-TV followup.So, I changed rule accordingly to prod.

**Comment by salilsamanvay** [comment]
as this report shows only those program which are hard coded, then once Karigar program issue is sorted then that will also have to be added in this report, so putting it on hold till we sort Karigar program issue.

**Comment by arjunk** [comment]
@salilsamanvay what is the Karigar program issue?

**Comment by vedfordev** [comment]
@Dinesh2019 we have not moved migration to prod. So currently pointing report to prerelease. [Report](https://reporting.avniproject.org/question/2585-partner-volunteer-and-total-student-report-prerelease)
