### ISSUE TITLE
[LAHI] Karigar - Student Report

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/LAHI#70]
**Context**
Lend a hand India team needs access to Students who are enrolled in the Karigar program with program type as batch along with their details of attendance which are captured agains the Karigar-batch.

**Goal**:
- [x] Create Karigar-Student Report
https://docs.google.com/spreadsheets/d/12M7sKauGH732iw5FJgWSz6m3-r1muzxUrLQMfn9WmKM/edit#gid=967278576

**Report Link:**  [Link](https://reporting.avniproject.org/question/2984-karigar-student-report-prerelease)

**Acceptance criteria**
- The report should bring data of students who are enrolled in Karigar and for whom "Select_program_KA" is selected as Batch.
- It should bring all students, exited as well as non-exited.

**Comment by utkarshavni** [comment]
5 hours for estimation provided by implementers. Should get completed in 2-3 hours as per suggested by Tech leads.

**Comment by utkarshavni** [comment]
@sachsk @vedfordev 
I have had a discussion with LAHI team - following are the points.
1. Students who are members of Karigar - Batch group, those students have not been enrolled in the Karigar program but the Batch group subject has been enrolled in the program.
2. The Attendance encounter has been created as a Program encounter. 
2. LAHI team was not aware that a Student could be enrolled in program and during that enrollment we could give Group Affiliation concept to add the student as a member in the group.
Question is:
1. If we remove the Batch group subjects from enrollment, and enroll the students in the program - can the tables be generated?
2. If we make Karigar Attendance encounter from Program encounter to General, will it require data migration and fresh sync?
What will be the efforts in order to make this report work? 
Moving the card to Tech lead review.

**Comment by sachsk** [comment]
Tech analysis :
To move the karigar program from karigar-batch(group subject) to the student (Person subject) we need to do the migration, or else we can ask the client to fill the data again and void the existing transactional data.

There are 38 karigar-batch(group subjects) enrolled in the karigar program which has 208 encounters (Karigar Attendance)

so we have migrate this data first to change the 

@utkarshavni  please schedule a call with the client to understand their approach.

**Comment by salilsamanvay** [comment]
first LAHI team will make changes in the implementation and data will be re-entered then we will prepare this report

**Comment by arjunk** [comment]
@salilsamanvay do we have an ETA for this from LAHI team?
