### ISSUE TITLE
Data Migration and Modification support for Karigar program to LAHI team 

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/LAHI#71]
LAHI team has created a program named as Karigar for which they have created group subject and enrolled that group into the program and attendance form is program encounter which is creating issue in reporting as well.

**Old Solution:**
- [ ] Change attendance form-> from program encounter to general encounter.
- [ ] Exit groups from Karigar program(lahi team).
- [ ] Create a new karigar program
- [ ] Enrol students into Karigar program via CSV upload(lahi team), Provide current enrolment data and void the enrolment(avni team)
- [ ] Upload the attendance enc via CSV (lahi team), provide current attendance data(avni team)
- [ ] Void current attendance encounter (avni team).
- [ ] Test the app (if its failing check the fast sync DB)

**New Solution :**
- [x] create new general encounter on karigar batch.
- [x] void attendance program encounter. (sql)
- [x] write a sql to insert the attendance from program encounter to general encounter (attendence) (sql)
- [x] enrol student into karigar program which was already enrolled via batch (Give to Lahi)

Existing data count:

- Total Karigar batch (group) --40-> 36 non voided
- Total enrolment-->42-->37 non voided-->25 non exited
- Total attendance encounter-->214-->208 non voided
--------------------------------

**Comment by sachsk** [comment]
Changes were done on prerelease but got an association error so I created a ticket.
Putting this card on hold.
https://avni.freshdesk.com/a/tickets/3399

**Comment by sachsk** [comment]
Now the product team has picked this up.
https://avni.freshdesk.com/a/tickets/3409

**Comment by vedfordev** [comment]
<img width="1793" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0F4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be02cee3b30474dcc27aec6f204a2bc19fe5ff2a/data.JPEG" alt="data.JPEG" />


## Understanding

**Comment by vedfordev** [comment]
Student - karigar Enrolment

### Tech Note :

1. From form name **Karigar Attendance and Progress Encounter**
    1. Removed mapping for **Karigar Atttendance**
    2. Changed Form Type to **Encounter**
2. Deleted encounter **Karigar Atttendance** web app 
3. Created new encounter_type **Karigar Attendance** and map with form name **Karigar Attendance and Progress Encounter** 
4. From form named **Karigar Enrolment** remove mapping of Karigar-Batch and add for student
5. Insert query to insert record from program_encounter to encounter [Link](https://github.com/avniproject/data-fixes/blob/main/lahi/program_encounter_to_encounter_migration.sql)

**Comment by vedfordev** [comment]
@sachsk/ @Dinesh2019  currently done in prerelease. after sanity test done we can move to prod

**Comment by Dinesh2019** [comment]
- [ ] App is getting crashed 

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenhBQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca52b3754da904cb3d2feb41ac40e7ba4c5ac057/Screen%20Recording%202024-02-08%20at%207.22.40%E2%80%AFPM.mov

**Comment by Dinesh2019** [comment]
Created the bug card for the above issue
https://github.com/avniproject/avni-client/issues/1293
