### ISSUE TITLE
LAHI | Program- State Report | Changes

### ISSUE THREAD

**Issue by Parth7223** [avniproject/LAHI#75]
- [x] 4 columns to be added in the 'Program-state report' in Metabase: 
       (i) No. of females currently enrolled 
       (ii) No. of males currently enrolled 
       (iii) No. of others currently enrolled
       (iv) Total no. of students currently enrolled

**Note:**- For all 4 columns mentioned above, students who have exited from the program should not be considered and only students who are currently enrolled should be populated.

**Report**- https://reporting.avniproject.org/question/2442-program-state-report

**Comment by adamsanadi6** [comment]
[Metabase Report link](https://reporting.avniproject.org/question/3094)
